### ISSUE TITLE
PowerMockito. Throw exception if a class wasn't prepared for test, but a user tries to use it

### ISSUE THREAD

**Issue by thekingnothing** [jayway/powermock#629]
PowerMock should throw exception if a class wasn't prepared for test, but a user tries to use it.
Cases then exception should be thrown
- [x] Use PowerMockito.mockStatic(MockWithStaticStateDemo.class) without @PrepareForTest (#604)
- [x] Use PowerMockito.spy(MockWithStaticStateDemo.class) without @PrepareForTest (#604)
- [x] Use when(MockWithStaticStateDemo.getState()) without @PrepareForTest or PowerMockito.mockStatic(MockWithStaticStateDemo.class) (#622)
