### ISSUE TITLE
Throw exception on verifyStatic and private if class wasn't prepared for test (@PrepareForTest(ClassWithStatic.class))

### ISSUE THREAD

**Issue by thekingnothing** [jayway/powermock#638]
PowerMock should throw exception if a class wasn't prepared for test, but a user tries to use it.
Cases then exception should be thrown
- [ ] Use PowerMockito.verifyStatic(MockWithStaticStateDemo.class) without @PrepareForTest or PowerMockito.mockStatic(MockWithStaticStateDemo.class) - for mocks.
- [ ] Use PowerMockito.verifyPrivate(MockWithStaticStateDemo.class) without @PrepareForTest or PowerMockito.mockStatic(MockWithStaticStateDemo.class) - for mocks.
- [ ] Use PowerMockito.verifyPrivate(mock) without @PrepareForTest or PowerMockito.mockStatic(MockWithStaticStateDemo.class) - for mocks.
